### ISSUE TITLE
Review Ashlar / DRIVER changes to get DRIVER dev environment running

### ISSUE THREAD

**Issue by ddohler** [azavea/ashlar-2018-fellowship#1]
And make pull requests to the parent projects if / when appropriate.

**Comment by jeancochrane** [comment]
DRIVER PR opened! https://github.com/WorldBank-Transport/DRIVER/pull/687

**Comment by jeancochrane** [comment]
I'm counting this as done; there's some outstanding review remaining to get the latest Ashlar changes pulled into `master`, but the changes are in for `develop`, and the remaining work is really a part of #23.
