### ISSUE TITLE
Package Ashlar for easy deployment

### ISSUE THREAD

**Issue by jeancochrane** [azavea/ashlar-2018-fellowship#19]
Related to #17, Ashlar will be more useful the easier it is to plug into a project. We should improve packaging and design it with specific implementations in mind, including:

- Dockerized setup for running as a standalone DB server with a JS app
    x. Setups with and without backend UI
    x. Potentially, templates for different kinds of app
- PyPi distribution for Django projects

**Comment by jeancochrane** [comment]
This issue has come a long way thanks to #23 and to the work that's gone into https://github.com/azavea/grout-server. Grout core is now installable with `pip install grout` and there are a couple of repos (including https://github.com/azavea/grout-blueprint and https://github.com/jeancochrane/philly-fliers) that use the server app in the way that's described in the [server app README](https://github.com/azavea/grout-server/blob/master/README.md).

One final piece of work is to update the two reference implementations so that they use the most recent versions + name (`grout-server`) of the server library. Beyond that, I'm curious if @ddohler and @flibbertigibbet have any thoughts on whether we can improve the packaging even more.

Three avenues that I'm considering:

1. Distribute the `grout-server` repo on PyPi to make it easily installable in Django projects.
    - Pros:
        - Increase the ease of installation for Django developers (Grout can run on the same port as the Django project, with the same DB connections).
    - Cons:
        - A lot of work to make things easy for a niche audience (Django developers).
        - Could potentially enhance the confusion between the `grout` and `grout-server` projects.

2. Distribute Docker images for the `grout-server` repo on a container repository like quay.io.
    - Pros:
        - Pulling an image from a container repository is cleaner way of managing dependencies than having to keep a clone/subtree of an external app in your project repo. 
    - Cons:
        - Grout Sever still expects a config file (`.env`) and still needs to be hooked into a container cluster, so while setup would be cleaner, it wouldn't necessarily be _easier_.

3. Do nothing; think more about packaging once real complaints come up.
    - Pros:
        - Doesn't waste any time on low-impact packaging improvements.
    - Cons:
        - If packaging is a major barrier to adoption of Grout, and our packaging isn't good enough to get anyone to even attempt to use it, we may never surface the complaints we need.

**Comment by ddohler** [comment]
I'm leaning toward #3 in favor of spending more time on the example app. As things stand, if we pursue #1 or #2, it may turn out that it doesn't help us very much, and then we'll be in the worst-case scenario of wasted effort and high barriers to adoption. I think at this stage we've got some awesome, obvious usability improvements finished, and so the best way to figure out what to do next is to try to do things with Grout and see where we run into friction.

**Comment by jeancochrane** [comment]
Cool! That lines up with how I'm feeling, too. Unless there are any other concerns, then, I'll close this for now. If I wind up bumping into clear packaging friction while developing the demo app then I can open more specific specific issues in the future.
