### ISSUE TITLE
Project direction brainstorming / planning

### ISSUE THREAD

**Issue by ddohler** [azavea/ashlar-2018-fellowship#2]
Some starting context: https://github.com/azavea/fellowship-program-website/pull/26

There are several options for how to develop Ashlar as part of this fellowship. We "picked" one as part of the discussion above, but that doesn't have to be the final decision. So it would be good to have a brainstorming and planning session to revisit that discussion and make a final decision now that @jeancochrane has gotten started on the project.

The goals of this discussion will be:
1. Review possible development goals for this project and discuss their benefits and drawbacks
2. If we think there is an obviously best development path, choose it. If not, we should figure out what information we need in order to make a decision.
3. Either way we go with number 2, come up with a series of tasks to either begin implementing our preferred solution, or to begin gathering information necessary to make the decision.

**Comment by jeancochrane** [comment]
Done! For sprint 1, I'm going to focus on building a reference implementation of Ashlar as it exists now. The reference implementation will act as a "test suite" of sorts, helping to define the core functions of Ashlar and figure out what parts of it should be abstracted out. Issues for this sprint coming shortly.

**Comment by ddohler** [comment]
Thanks for creating issues for this sprint!
