### ISSUE TITLE
Split off the JS API and distribute it on NPM

### ISSUE THREAD

**Issue by jeancochrane** [azavea/ashlar-2018-fellowship#20]
The DRIVER frontend apps already sort of implement a JS API for making it easier to interact with Ashlar from the client side. Splitting this off into a separate module packaged via e.g. NPM would be a big boost to frontend development.

**Comment by ddohler** [comment]
I think this is a super good idea and it might alleviate some of the concerns around picking a particular frontend framework, if there was a vanilla JS library that could be used anywhere interact with an Ashlar service.

**Comment by jeancochrane** [comment]
API development is coming along nicely in the demo app. Changing the title to reflect the next pieces of substantial work.

**Comment by jeancochrane** [comment]
JS bindings is a cool idea, but the value proposition is not really clear since we don't have external users and we don't know what they'd want. I'll update the Grout docs to point to the potential of these bindings, but for now we're not going to split and distribute them on NPM.
