### ISSUE TITLE
Bring schema editor up to date with a modern framework

### ISSUE THREAD

**Issue by jeancochrane** [azavea/ashlar-2018-fellowship#21]
Related to #14, the schema editor is currently written in a deprecated version of AngularJS. It should be updated to work with a modern framework.

**Comment by ddohler** [comment]
Another reason to do this is that the existing code relies on Bower, which is officially deprecated and unmaintained in favor of `yarn`.

**Comment by jeancochrane** [comment]
AngularJS 1.7 was released on July 1st. It'll be the last version of AngularJS, and will recieve long-term support for three years. [Blog post here.](https://blog.angular.io/stable-angularjs-and-long-term-support-7e077635ee9c)

As fun as it would be to rewrite the schema editor in a new framework, it seems unlikely to me that we'll have enough time during this fellowship. A faster plan for closing this issue might be:

1. Upgrade to AngularJS 1.7
2. Remove Bower and migrate to Yarn for package management
3. Attempt to update as many dependencies as possible
4. Improve test coverage

**Comment by ddohler** [comment]
I think those are all great short-term improvements! :+1:

**Comment by jeancochrane** [comment]
Done in https://github.com/azavea/grout-schema-editor/pull/5.
