### ISSUE TITLE
Get Ashlar onto PyPi

### ISSUE THREAD

**Issue by ddohler** [azavea/ashlar-2018-fellowship#23]
That'll make it much easier for other people to install it.

**Comment by ddohler** [comment]
(Component of #19 but I thought this was something we might want to do earlier than some of the other parts of that)

**Comment by jeancochrane** [comment]
As of https://github.com/azavea/ashlar/pull/81 deployments to PyPi are all set, but as #26 points out, `ashlar` is already taken on PyPi so we can't publish the package with that name. Keeping this open until we find a new direction per #26 and decide what we want to do about PyPi distribution.

**Comment by jeancochrane** [comment]
Done! https://pypi.org/project/grout/
