### ISSUE TITLE
Change authentication token routes in Grout Server

### ISSUE THREAD

**Issue by jeancochrane** [azavea/ashlar-2018-fellowship#42]
Right now the default route for getting an authentication token from the Grout Server API is `/api-token-auth/`. All other API methods are served from `/api/`. This makes it annoying to run a Grout Server under a reverse proxy -- all calls to `/api/` can be safely redirected to the running Grout Server, but `/api-token-auth/` either A) requires its own location block or B) gets caught by the default `/` location block and passed to the wrong process/directory.

This whole situation would be simpler if the token request endpoint was underneath the `/api/` location -- something like `/api/token/`.

**Comment by jeancochrane** [comment]
Note that this will require a change to the Schema Editor as well, which uses this endpoint for authentication.

**Comment by ddohler** [comment]
Yeah, that was an unfortunate copy-paste; I think switching to `/api/token/` would be good. I've also seen `/api/auth/token/<action>` which is (maybe?) slightly nicer organization if you want to add other authentication methods later.

**Comment by jeancochrane** [comment]
Done in https://github.com/azavea/grout-server/pull/6.
