### ISSUE TITLE
Fix regression in JSONB filters

### ISSUE THREAD

**Issue by jeancochrane** [azavea/ashlar-2018-fellowship#47]
At some point (most likely in the course of #12) we introduced a bug into Grout that is causing `jsonb` filters to never return Records, even when the condition should pass. Per [@flibbertigibbet's description](https://github.com/jeancochrane/philly-fliers/pull/4#pullrequestreview-142593694):

> On entering any text in the search, I get no results, even if the text is an exact match. Clearing the filter still returns the one sample record.

**Comment by jeancochrane** [comment]
On second thought, this bug may not be in Grout core. The initial failing test I had written was malformed, and was failing for the wrong reasons; now with two new appropriate tests, [the tests are passing as expected](https://travis-ci.org/azavea/grout/builds/411356201). However, when trying to run equivalent queries by entering them into the URL of the running Grout Server instance, the filters continue to fail. Something is potentially going wrong in the interaction between Grout Server and Grout core.

**Comment by jeancochrane** [comment]
Finally figured it out! Turns out that the custom JSONB lookup wasn't being registered properly. This one was a real doozy.

The bug had to do with the particular way that the JSONField filters behave: by default, JSONField allows you to perform nested searches using the filter keys, e.g. if you have a JSONField like:

```python
class Record(models.Model):
    data = JSONField()

Record.objects.create(data={
  "foo": {
    "bar": "baz"
  }
})
```

You can search it by chaining filter keys:

```python
Record.objects.query(data__foo__bar=baz)
```

This is generally really handy! Except that our custom JSONB filter needs to use that same real estate in order to work, since it uses a custom filter key syntax like:

```python
Record.objects.filter(data__jsonb={"foo": {"bar": {"_rule_type": "containment", "contains": "baz"}})
````

Read from the perspective of the built-in JSONField filter, however, the above call to `data__jsonb` looks like a call to filter a JSON with the following structure:

```json
{
  "jsonb": {"foo": {"bar": {"_rule_type": "containment", "contains": "baz"}}
}
```

That's no good! Luckily, we can register custom lookups that will override this behavior. I thought we had accomplished this in [`grout.lookups`](https://github.com/azavea/grout/blob/ef1fa6d0edcdf51e098600e8ed9e3b0d5d1ece46/grout/lookups.py#L372-L376) by using the `@register_lookup` decorator:

```python
@JSONField.register_lookup
class JSONLookup(Lookup):
    """
    A custom lookup using the FilterTree to implement nested queries for JSONFields.
    """
```

Unfortunately, I didn't look closely enough at [the documentation for custom lookups](https://docs.djangoproject.com/en/2.0/howto/custom-lookups/#a-simple-lookup-example), which notes an important caveat:

> You will need to ensure that this registration happens before you try to create any querysets using it. You could place the implementation in a models.py file, or register the lookup in the ready() method of an AppConfig.

Ultimately, this was the source of the bug, and also of the strange behavior where unit tests passed but QA tests didn't: `grout.lookups` wasn't being imported anywhere in the code, _except for in the tests!_ When the application ran on the server, the lookup would never get registered, and the filter would silently default to the built-in JSONField filter syntax. In the tests, however, where the lookup gets imported in the `jsonb_field_testing` test module, the custom lookup would perform as expected.

**Comment by ddohler** [comment]
Very interesting! Nice sleuthing!
